### ISSUE TITLE
NullPointerException when loading file conveyor-config.xml

### ISSUE THREAD

**Issue by jprusch** [echocat/adam#57]
Hi,
I'm getting a NPE when stopping Confluence:

```
2016-05-20 11:45:12,476 ERROR [FelixStartLevel] [confluence.conveyor.config.ConveyorConfigurationProvider] fail Caught exception while loading file /org/echocat/adam/convoyed/conveyor-config.xml
org.randombits.confluence.conveyor.config.ConveyorException: Caught exception while loading file /org/echocat/adam/convoyed/conveyor-config.xml
	at org.randombits.confluence.conveyor.config.ConveyorConfigurationProvider.loadConfigurationFile(ConveyorConfigurationProvider.java:236)
	at org.randombits.confluence.conveyor.config.ConveyorConfigurationProvider.init(ConveyorConfigurationProvider.java:197)
	at com.opensymphony.xwork.config.impl.DefaultConfiguration.reload(DefaultConfiguration.java:85)
	at com.atlassian.confluence.event.listeners.XWorkChangeListener.handleXWorkStateChangeEvent(XWorkChangeListener.java:13)
...
	at org.apache.felix.framework.Felix.stopBundle(Felix.java:2520)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1309)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.opensymphony.util.ClassLoaderUtil.getResource(ClassLoaderUtil.java:40)
	at com.opensymphony.util.FileManager.loadFile(FileManager.java:67)
	at org.randombits.confluence.conveyor.config.ConveyorConfigurationProvider.getInputStream(ConveyorConfigurationProvider.java:279)
	at org.randombits.confluence.conveyor.config.ConveyorConfigurationProvider.loadConfigurationFile(ConveyorConfigurationProvider.java:227)
	... 58 more
```

Doesn't seem bad, just letting you know.

Thanks,

Jan-Peter

**Comment by blaubaer** [comment]
@jprusch sorry but I'am not able to reproduce the problem. Could you provide more information for that? Context, how this was produced, more logs etc.

**Comment by jprusch** [comment]
Not happening anymore.
