### ISSUE TITLE
Future of this plugin

### ISSUE THREAD

**Issue by raphrenn** [echocat/adam#73]
Hi,

we've noticed that the adam plugin has been removed from the Atlassian Marketplace.
Does this mean the project is shut down? We'd like to know if we have to start looking for an alternative.

Kind regards,
Raphael

**Comment by jprusch** [comment]
Sehr geehrte Damen und Herren,
ich bin vom 9.9.-11.9. nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.
Ihre Mail wird NICHT weitergeleitet und nach meiner Rückkehr bearbeitet.
In dringende Fällen wenden Sie sich bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de)
Mit freundlichen Grüßen

i.V. Jan-Peter Rusch

TEL +49 (0)571-502-145 | FAX +49 (0)571-502-66-145
j.rusch@schaeferbarthold.de
______________________________________________________________________
Schäferbarthold GmbH
Erbeweg 2-12 | 32457 Porta Westfalica | Deutschland
www.schaeferbarthold.de
Schäferbarthold GmbH: Amtsgericht Bad Oeynhausen HRB 3748
Geschäftsführer: Dr. Volker Schäferbarthold, Dr. Christian Schäferbarthold, Wolfgang Schäferbarthold

**Comment by alexat** [comment]
Version fixing plugin load error in Confluence 7 (7.0.1) is available in my repo

https://github.com/alexat/adam/releases

Please note that I do not support this plugin, nor in any way related to it, just did what it required to make it load and work (for me) in 7.0.1.

**Comment by jprusch** [comment]
Thanks @alexat 
Will try & give feedback on Confluence 7.3.1

**Comment by jprusch** [comment]
Hi @alexat 
I did a test of https://github.com/alexat/adam/releases with Confluence 7.3.1
With the new version Confluence starts up & I can log in (wasn't possible in latest echocat version).
But the Persons-Page cannot be loaded. I'll get an error 500 with

`Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.echocat.adam.configuration.ConfigurationMarshaller
	at org.echocat.adam.configuration.ConfigurationRepository.getInternal(ConfigurationRepository.java:103)
	at org.echocat.adam.configuration.ConfigurationRepository.get(ConfigurationRepository.java:73)
	at org.echocat.adam.report.ReportProvider.getConfiguration(ReportProvider.java:564)
	at org.echocat.adam.report.ReportProvider.tryProvideViewable(ReportProvider.java:97)
	at org.echocat.adam.profile.ExtendedPeopleDirectoryAction.getEffectiveReport(ExtendedPeopleDirectoryAction.java:308)
	at org.echocat.adam.profile.ExtendedPeopleDirectoryAction.doBrowse(ExtendedPeopleDirectoryAction.java:97)
	... 393 more
2020-02-14 14:31:34,707 INFO [ajp-nio-xxx.xxx.xxx.xxx-8009-exec-12] [atlassian.confluence.status.SystemErrorInformationLogger] writeToLog 
Request Unique ID : 0b5fd580-ebfb-431f-9ced-86410adc3eff
--------------------------
JVM Stats
--------------------------
xmx = 3221225472
usedNonHeap = 545093648
availableHeap = 2374591832
availableNonHeap = -1
allocatedHeap = 1073741824
freeAllocatedHeap = 227108184
maxNonHeap = -1
availablePermGen = 0
maxPermGen = -1
maxHeap = 3221225472
usedHeap = 846633640
usedPermGen = -1
xms = 1073741824
--------------------------
Request Information
--------------------------
URL: https://SERVER/confluence/500page.jsp
Scheme: https
Server: SERVER
Port: 443
URI: /confluence/500page.jsp
Context Path: /confluence
Servlet Path: /500page.jsp
Path Info: null
Query String: null
--------------------------
Attributes
--------------------------
javax.servlet.forward.request_uri: /confluence/browsepeople.action
javax.servlet.forward.context_path: /confluence
javax.servlet.forward.servlet_path: /browsepeople.action
javax.servlet.forward.mapping: org.apache.catalina.core.ApplicationMapping$MappingImpl@6fe7c647
javamelody.injectorWrapped: true
javax.servlet.error.status_code: 500
com.atlassian.confluence.impl.profiling.DecoratorTimings: com.atlassian.confluence.impl.profiling.DecoratorTimings@24f67dc2
com.opensymphony.sitemesh.APPLIED_ONCE: true
__cleanup_recursion_counter: 0
com.atlassian.confluence.util.message.MessagesDecoratorFilter__already_filtered__: true
com.atlassian.confluence.web.filter.validateparam.RequestParamValidationFilter_already_filtered: true
atlassian.core.seraph.original.url: /500page.jsp
com.atlassian.labs.botkiller.BotKillerFilter: true
com.atlassian.gzipfilter.GzipFilter_already_filtered: true
Confluence-Request-Time: 1581687093586
javamelody.request: /browsepeople.action GET
com.atlassian.confluence.web.ConfluenceJohnsonFilter_already_filtered: true
com.atlassian.seraph.auth.LoginReason: OK
webwork.valueStack: com.opensymphony.xwork.util.OgnlValueStack@61002f9f
confluence.themecontext: com.atlassian.confluence.themes.ThemeContext@ecff5ee
javax.servlet.error.message: 
javax.servlet.error.servlet_name: action
com.opensymphony.sitemesh.USINGSTREAM: false
B3-TraceId: 8cc53030127109
loginfilter.already.filtered: true
javax.servlet.jsp.jspException: java.lang.reflect.InvocationTargetException
javax.servlet.error.request_uri: /confluence/browsepeople.action
com.atlassian.core.filters.HeaderSanitisingFilter_already_filtered: true
com.atlassian.prettyurls.filter.PrettyUrlsSiteMeshFixupFilter: true
javax.servlet.error.exception: java.lang.reflect.InvocationTargetException
os_securityfilter_already_filtered: true
com.atlassian.prettyurls.filter.PrettyUrlsSiteMeshFilter: true
--------------------------
Parameters
--------------------------
caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
caused by: java.lang.NoClassDefFoundError: Could not initialize class org.echocat.adam.configuration.ConfigurationMarshaller
at org.echocat.adam.configuration.ConfigurationRepository.getInternal(ConfigurationRepository.java:103)`

As I'm not the master of app development for Confluence, you might want to take a look... I'm eager to test any new version.
Best regards
JP

**Comment by alexat** [comment]
I have finally migrated to 7.4 myself so will try to see what happens and possibly fix.

**Comment by jprusch** [comment]
Works with: https://github.com/sanjay900/adam

**Comment by alexat** [comment]
Thanks for pointing out the repo, I've merged changes from both sanjay900 and cwittenb to my branch and posted a combined 'release' so both sets of changes are in.

https://github.com/alexat/adam/releases/tag/0.1.16

Remember this is totally untested, so use at your own risk.

**Comment by jprusch** [comment]
As always ;-) Thanks for still looking after this amazing little addon. We dropped our paper printed hard to update phone list & rely on our Adam for department lists with phone, email, etc...
Didn't find any errors using the sanjay900 repo.
