### ISSUE TITLE
Warning on sync event listener with Confluence 7.11.1

### ISSUE THREAD

**Issue by jprusch** [echocat/adam#77]
Hi,
I see the following warning in the application log.
Not sure, if this is critical as the users can login & the adam pages are displayed.

`2021-03-07 14:03:15,760 WARN [ajp-nio-192.168.x.y-PORT-exec-11 url: /confluence/plugins/servlet/secsignid] [**echocat.adam.synchronization.LdapDirectorySynchronizationRequiredEventListener**] handleLogin The user xyz could not be synchronized. This means that this user could be out of date.
 -- referer: https://THEDOMAIN/confluence/plugins/servlet/secsignid | url: /confluence/plugins/servlet/secsignid | traceId: 260140bc9bc4558b | userName: anonymous
java.lang.RuntimeException: Could not check if com.atlassian.crowd.directory.MicrosoftActiveDirectory is loadable.
	at org.echocat.adam.directory.ExtendingLDAPDirectoryInstanceLoader.canLoad(ExtendingLDAPDirectoryInstanceLoader.java:93)
	at org.echocat.adam.synchronization.LdapDirectorySynchronizer.findRemoteDirectoryOf(LdapDirectorySynchronizer.java:267)
	at org.echocat.adam.synchronization.LdapDirectorySynchronizer$3.nextIterator(LdapDirectorySynchronizer.java:170)
	at org.echocat.adam.synchronization.LdapDirectorySynchronizer$3.nextIterator(LdapDirectorySynchronizer.java:166)
	at org.echocat.jomon.runtime.iterators.ChainedIterator.hasNext(ChainedIterator.java:51)
	at org.echocat.jomon.runtime.iterators.ChainedIterator.hasNext(ChainedIterator.java:48)
	at org.echocat.jomon.runtime.iterators.IteratorUtils$4.computeNext(IteratorUtils.java:141)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at org.echocat.jomon.runtime.iterators.IteratorUtils$3.hasNext(IteratorUtils.java:109)
	at org.echocat.adam.synchronization.LdapDirectorySynchronizer.synchronize(LdapDirectorySynchronizer.java:215)
	at org.echocat.adam.synchronization.LdapDirectorySynchronizer.synchronize(LdapDirectorySynchronizer.java:204)
	at org.echocat.adam.synchronization.LdapDirectorySynchronizationRequiredEventListener.handleLogin(LdapDirectorySynchronizationRequiredEventListener.java:46)
	at jdk.internal.reflect.GeneratedMethodAccessor2253.invoke(Unknown Source)`

As this warning is verbose, I set echocat.adam to log level ERROR in Confluence.

Jan

**Comment by AlexAT** [comment]
Please check my master branch again.
https://github.com/AlexAT/adam

I didn't test it deep as always, but works for me.

**Comment by jprusch** [comment]
I can pick it up in your repo.

**Comment by AlexAT** [comment]
Here you go: https://github.com/AlexAT/adam/releases/tag/0.1.17
Built with AdoptOpenJDK 11.0.8

**Comment by jprusch** [comment]
Thanks! Works great, no more errors.
